services:
  db:
    image: postgres:13.0-alpine

    volumes:
      - db_volume:/var/lib/postgresql/data/

    env_file:
      - ./.env


  backend:
    image: galenfea/foodgram_backend:latest
    restart: on-failure

    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

    depends_on:
      - db

    env_file:
      - ./.env
    # command: >
    #  bash -c "python manage.py collectstatic
    #  && gunicorn foodgram.wsgi:application --bind 0:8000"

  frontend:
    image: galenfea/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

    depends_on:
      - backend


  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - frontend

volumes:
  static_volume:
  media_volume:
  db_volume:
